### ISSUE TITLE
Update for AS 2.1.1

### ISSUE THREAD

**Issue by JPry** [Prospress/action-scheduler-high-volume#2]
With the merge of Prospress/action-scheduler#209, we'll need  to adjust the code here to use the new filter.

**Comment by lkraav** [comment]
```
[11-Jan-2019 02:55:18 UTC] PHP Notice:  action_scheduler_maximum_execution_time is <strong>deprecated</strong> since version 2.1.1! Use action_scheduler_queue_runner_time_limit instead. in /home/convers/public_html/institute/wp-includes/functions.php on line 3888
```

Indeed. Is this a difficult effort?

**Comment by thenbrent** [comment]
@lkraav no, and it's already been done in the plugin itself (just not versioned). See https://github.com/Prospress/action-scheduler-high-volume/commit/9a31fdf622db3ed89e34099bfef0edd06fcbce29. :)

**Comment by lkraav** [comment]
@thenbrent but I just cloned this repo, and it's spewing notices all over debug log.

https://github.com/Prospress/action-scheduler-high-volume/blob/master/action-scheduler-high-volume.php#L121 also shows the action still there. What am I missing?

**Comment by thenbrent** [comment]
Ah. That action can be removed. The `'action_scheduler_queue_runner_time_limit'` filter is now used as part of a single source on the time limit (that's the reason for the name changes). I'll get that fixed up now.

**Comment by thenbrent** [comment]
It looks like the wrong filters were removed in SHA: 9a31fdf. Those ones don't need to be removed. This is now fixed with https://github.com/Prospress/action-scheduler-high-volume/compare/4e76eae...e2feaac
